// AUTO-GENERATED by scripts/generate-showroom.cjs
import React, { useState } from 'react';
import { ThemeProvider, useTheme } from './design-system/ThemeProvider';
import { typography, darkTheme } from './design-system/tokens';
import { Accordion } from './design-system/components/Accordion';
import { Alert } from './design-system/components/Alert';
import { Autocomplete } from './design-system/components/Autocomplete';
import { BarGraph } from './design-system/components/BarGraph';
import { BorderRadius } from './design-system/components/BorderRadius';
import { Button } from './design-system/components/Button';
import { Cell } from './design-system/components/Cell';
import { Chip } from './design-system/components/Chip';
import { DatePicker } from './design-system/components/DatePicker';
import { DealerBranch } from './design-system/components/DealerBranch';
import { DealerContactTile } from './design-system/components/DealerContactTile';
import { DealerLocation } from './design-system/components/DealerLocation';
import { DealerMap } from './design-system/components/DealerMap';
import { DealerOpeningHours } from './design-system/components/DealerOpeningHours';
import { DealerService } from './design-system/components/DealerService';
import { DecorativeCarCard } from './design-system/components/DecorativeCarCard';
import { DecorativeText } from './design-system/components/DecorativeText';
import { Divider } from './design-system/components/Divider';
import { DotStack } from './design-system/components/DotStack';
import { FocusCatcher } from './design-system/components/FocusCatcher';
import { FocusOutline } from './design-system/components/FocusOutline';
import { Footer } from './design-system/components/Footer';
import { FormContainer } from './design-system/components/FormContainer';
import { FormHelperText } from './design-system/components/FormHelperText';
import { FormTypography } from './design-system/components/FormTypography';
import { GlobalFooter } from './design-system/components/GlobalFooter';
import { GlobalStylesScope } from './design-system/components/GlobalStylesScope';
import { IconButton } from './design-system/components/IconButton';
import { IconLink } from './design-system/components/IconLink';
import { InputBorder } from './design-system/components/InputBorder';
import { InputLabel } from './design-system/components/InputLabel';
import { Label } from './design-system/components/Label';
import { LexusMap } from './design-system/components/LexusMap';
import { List } from './design-system/components/List';
import { LoadingSpinner } from './design-system/components/LoadingSpinner';
import { ProgressBar } from './design-system/components/ProgressBar';
import { ProgressStepper } from './design-system/components/ProgressStepper';
import { Responsive } from './design-system/components/Responsive';
import { ScrollIndicator } from './design-system/components/ScrollIndicator';
import { Select } from './design-system/components/Select';
import { Shadow } from './design-system/components/Shadow';
import { StickyPageBanner } from './design-system/components/StickyPageBanner';
import { Surface } from './design-system/components/Surface';
import { TextField } from './design-system/components/TextField';
import { TextInput } from './design-system/components/TextInput';
import { ThemeVariantScope } from './design-system/components/ThemeVariantScope';
import { TooltipPopup } from './design-system/components/TooltipPopup';
import { TooltipWithIcon } from './design-system/components/TooltipWithIcon';
import { TopBanner } from './design-system/components/TopBanner';
import { VehiclePlaceholder } from './design-system/components/VehiclePlaceholder';
import { AccordionGroup } from './design-system/layouts/AccordionGroup';
import { AnimateInView } from './design-system/layouts/AnimateInView';
import { Box } from './design-system/layouts/Box';
import { Card } from './design-system/layouts/Card';
import { Container } from './design-system/layouts/Container';
import { ContentBlock } from './design-system/layouts/ContentBlock';
import { ContentBlockInnerContainer } from './design-system/layouts/ContentBlockInnerContainer';
import { DynamicMedia } from './design-system/layouts/DynamicMedia';
import { FormSection } from './design-system/layouts/FormSection';
import { Grid } from './design-system/layouts/Grid';
import { ImageWithTooltip } from './design-system/layouts/ImageWithTooltip';
import { Layers } from './design-system/layouts/Layers';
import { Modal } from './design-system/layouts/Modal';
import { Oriented } from './design-system/layouts/Oriented';
import { Popover } from './design-system/layouts/Popover';
import { SlideShow } from './design-system/layouts/SlideShow';
import { Stack } from './design-system/layouts/Stack';
import { Tabs } from './design-system/layouts/Tabs';
import { VerticalScroll } from './design-system/layouts/VerticalScroll';
import { AdvancedCheckbox } from './design-system/compositions/AdvancedCheckbox';
import { AdvancedRadio } from './design-system/compositions/AdvancedRadio';
import { ButtonGroup } from './design-system/compositions/ButtonGroup';
import { CarCard } from './design-system/compositions/CarCard';
import { CardTable } from './design-system/compositions/CardTable';
import { CardWithHeader } from './design-system/compositions/CardWithHeader';
import { Carousel } from './design-system/compositions/Carousel';
import { CarouselWithCards } from './design-system/compositions/CarouselWithCards';
import { Checkbox } from './design-system/compositions/Checkbox';
import { CheckboxGroup } from './design-system/compositions/CheckboxGroup';
import { CookieConsent } from './design-system/compositions/CookieConsent';
import { FilterSlide } from './design-system/compositions/FilterSlide';
import { GenericTile } from './design-system/compositions/GenericTile';
import { GridWithCards } from './design-system/compositions/GridWithCards';
import { HeadingAndText } from './design-system/compositions/HeadingAndText';
import { Hero } from './design-system/compositions/Hero';
import { LinkList } from './design-system/compositions/LinkList';
import { LookupForm } from './design-system/compositions/LookupForm';
import { ModalSheet } from './design-system/compositions/ModalSheet';
import { MultiRow } from './design-system/compositions/MultiRow';
import { PWABottomNavigation } from './design-system/compositions/PWABottomNavigation';
import { PageHeader } from './design-system/compositions/PageHeader';
import { Radio } from './design-system/compositions/Radio';
import { RadioGroup } from './design-system/compositions/RadioGroup';
import { Row } from './design-system/compositions/Row';
import { SearchCard } from './design-system/compositions/SearchCard';
import { SearchPreviewPopover } from './design-system/compositions/SearchPreviewPopover';
import { SecondaryNavigationBar } from './design-system/compositions/SecondaryNavigationBar';
import { ShadedRow } from './design-system/compositions/ShadedRow';
import { SlideShowWithHero } from './design-system/compositions/SlideShowWithHero';
import { TableOfContent } from './design-system/compositions/TableOfContent';
import { Tooltip } from './design-system/compositions/Tooltip';

const ALL_COMPONENTS = {
  "Components": [
    "Accordion",
    "Alert",
    "Autocomplete",
    "BarGraph",
    "BorderRadius",
    "Button",
    "Cell",
    "Chip",
    "DatePicker",
    "DealerBranch",
    "DealerContactTile",
    "DealerLocation",
    "DealerMap",
    "DealerOpeningHours",
    "DealerService",
    "DecorativeCarCard",
    "DecorativeText",
    "Divider",
    "DotStack",
    "FocusCatcher",
    "FocusOutline",
    "Footer",
    "FormContainer",
    "FormHelperText",
    "FormTypography",
    "GlobalFooter",
    "GlobalStylesScope",
    "IconButton",
    "IconLink",
    "InputBorder",
    "InputLabel",
    "Label",
    "LexusMap",
    "List",
    "LoadingSpinner",
    "ProgressBar",
    "ProgressStepper",
    "Responsive",
    "ScrollIndicator",
    "Select",
    "Shadow",
    "StickyPageBanner",
    "Surface",
    "TextField",
    "TextInput",
    "ThemeVariantScope",
    "TooltipPopup",
    "TooltipWithIcon",
    "TopBanner",
    "VehiclePlaceholder"
  ],
  "Layouts": [
    "AccordionGroup",
    "AnimateInView",
    "Box",
    "Card",
    "Container",
    "ContentBlock",
    "ContentBlockInnerContainer",
    "DynamicMedia",
    "FormSection",
    "Grid",
    "ImageWithTooltip",
    "Layers",
    "Modal",
    "Oriented",
    "Popover",
    "SlideShow",
    "Stack",
    "Tabs",
    "VerticalScroll"
  ],
  "Compositions": [
    "AdvancedCheckbox",
    "AdvancedRadio",
    "ButtonGroup",
    "CarCard",
    "CardTable",
    "CardWithHeader",
    "Carousel",
    "CarouselWithCards",
    "Checkbox",
    "CheckboxGroup",
    "CookieConsent",
    "FilterSlide",
    "GenericTile",
    "GridWithCards",
    "HeadingAndText",
    "Hero",
    "LinkList",
    "LookupForm",
    "ModalSheet",
    "MultiRow",
    "PWABottomNavigation",
    "PageHeader",
    "Radio",
    "RadioGroup",
    "Row",
    "SearchCard",
    "SearchPreviewPopover",
    "SecondaryNavigationBar",
    "ShadedRow",
    "SlideShowWithHero",
    "TableOfContent",
    "Tooltip"
  ]
};
const MAPPED_COMPONENTS: Record<string, React.FC<any>> = {
  "Accordion": Accordion,
  "Alert": Alert,
  "Autocomplete": Autocomplete,
  "BarGraph": BarGraph,
  "BorderRadius": BorderRadius,
  "Button": Button,
  "Cell": Cell,
  "Chip": Chip,
  "DatePicker": DatePicker,
  "DealerBranch": DealerBranch,
  "DealerContactTile": DealerContactTile,
  "DealerLocation": DealerLocation,
  "DealerMap": DealerMap,
  "DealerOpeningHours": DealerOpeningHours,
  "DealerService": DealerService,
  "DecorativeCarCard": DecorativeCarCard,
  "DecorativeText": DecorativeText,
  "Divider": Divider,
  "DotStack": DotStack,
  "FocusCatcher": FocusCatcher,
  "FocusOutline": FocusOutline,
  "Footer": Footer,
  "FormContainer": FormContainer,
  "FormHelperText": FormHelperText,
  "FormTypography": FormTypography,
  "GlobalFooter": GlobalFooter,
  "GlobalStylesScope": GlobalStylesScope,
  "IconButton": IconButton,
  "IconLink": IconLink,
  "InputBorder": InputBorder,
  "InputLabel": InputLabel,
  "Label": Label,
  "LexusMap": LexusMap,
  "List": List,
  "LoadingSpinner": LoadingSpinner,
  "ProgressBar": ProgressBar,
  "ProgressStepper": ProgressStepper,
  "Responsive": Responsive,
  "ScrollIndicator": ScrollIndicator,
  "Select": Select,
  "Shadow": Shadow,
  "StickyPageBanner": StickyPageBanner,
  "Surface": Surface,
  "TextField": TextField,
  "TextInput": TextInput,
  "ThemeVariantScope": ThemeVariantScope,
  "TooltipPopup": TooltipPopup,
  "TooltipWithIcon": TooltipWithIcon,
  "TopBanner": TopBanner,
  "VehiclePlaceholder": VehiclePlaceholder,
  "AccordionGroup": AccordionGroup,
  "AnimateInView": AnimateInView,
  "Box": Box,
  "Card": Card,
  "Container": Container,
  "ContentBlock": ContentBlock,
  "ContentBlockInnerContainer": ContentBlockInnerContainer,
  "DynamicMedia": DynamicMedia,
  "FormSection": FormSection,
  "Grid": Grid,
  "ImageWithTooltip": ImageWithTooltip,
  "Layers": Layers,
  "Modal": Modal,
  "Oriented": Oriented,
  "Popover": Popover,
  "SlideShow": SlideShow,
  "Stack": Stack,
  "Tabs": Tabs,
  "VerticalScroll": VerticalScroll,
  "AdvancedCheckbox": AdvancedCheckbox,
  "AdvancedRadio": AdvancedRadio,
  "ButtonGroup": ButtonGroup,
  "CarCard": CarCard,
  "CardTable": CardTable,
  "CardWithHeader": CardWithHeader,
  "Carousel": Carousel,
  "CarouselWithCards": CarouselWithCards,
  "Checkbox": Checkbox,
  "CheckboxGroup": CheckboxGroup,
  "CookieConsent": CookieConsent,
  "FilterSlide": FilterSlide,
  "GenericTile": GenericTile,
  "GridWithCards": GridWithCards,
  "HeadingAndText": HeadingAndText,
  "Hero": Hero,
  "LinkList": LinkList,
  "LookupForm": LookupForm,
  "ModalSheet": ModalSheet,
  "MultiRow": MultiRow,
  "PWABottomNavigation": PWABottomNavigation,
  "PageHeader": PageHeader,
  "Radio": Radio,
  "RadioGroup": RadioGroup,
  "Row": Row,
  "SearchCard": SearchCard,
  "SearchPreviewPopover": SearchPreviewPopover,
  "SecondaryNavigationBar": SecondaryNavigationBar,
  "ShadedRow": ShadedRow,
  "SlideShowWithHero": SlideShowWithHero,
  "TableOfContent": TableOfContent,
  "Tooltip": Tooltip,
};

function Sidebar({ selected, onSelect }: { selected: string, onSelect: (n: string) => void }) {
  const { tokens } = useTheme();
  return (
    <nav style={{
      width: 280,
      background: tokens.canvasDefault,
      borderRight: `1px solid ${tokens.modifiersMidlight}`,
      height: 'calc(100vh - 64px)',
      overflowY: 'auto',
      position: 'fixed',
      top: 64,
      left: 0,
      padding: '32px 0'
    }}>
      {Object.entries(ALL_COMPONENTS).map(([category, items]) => (
        <div key={category} style={{ marginBottom: 32 }}>
          <div style={{
            fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '1.44px',
            color: tokens.foregroundDefault, opacity: 0.5, padding: '0 32px', marginBottom: 12,
            fontFamily: typography.fontFamilies.primary
          }}>
            {category}
          </div>
          {items.map(name => (
            <div
              key={name}
              onClick={() => onSelect(name)}
              style={{
                padding: '10px 32px', cursor: 'pointer', fontSize: 14,
                fontFamily: typography.fontFamilies.primary,
                color: selected === name ? tokens.accentPrimaryDefault : tokens.foregroundDefault,
                backgroundColor: selected === name ? tokens.elevationRaisedDefault : 'transparent',
                borderRight: selected === name ? `3px solid ${tokens.accentPrimaryDefault}` : '3px solid transparent',
                fontWeight: selected === name ? 600 : 400,
                transition: 'all 0.2s'
              }}
            >
              {name.replace(/([A-Z])/g, ' $1').trim()}
            </div>
          ))}
        </div>
      ))}
    </nav>
  );
}

function Topbar() {
  const { tokens, mode, toggleMode } = useTheme();
  return (
    <header style={{
      height: 64, borderBottom: `1px solid ${tokens.modifiersMidlight}`,
      backgroundColor: tokens.canvasDefault, display: 'flex', alignItems: 'center',
      justifyContent: 'space-between', padding: '0 32px', position: 'fixed', top: 0, left: 0, right: 0, zIndex: 100
    }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
        <div style={{ width: 28, height: 28, background: '#D60000', borderRadius: 4 }}></div>
        <span style={{ 
            fontWeight: 700, fontSize: 20, color: tokens.foregroundDefault,
            fontFamily: typography.fontFamilies.primary, letterSpacing: '-0.5px' 
        }}>
          LK Design GEL
        </span>
      </div>
      <button onClick={toggleMode} style={{
        background: 'transparent', border: `1px solid ${tokens.modifiersMidlight}`,
        padding: '8px 16px', borderRadius: 20, cursor: 'pointer', color: tokens.foregroundDefault,
        fontFamily: typography.fontFamilies.primary, fontWeight: 600, fontSize: 12
      }}>
        {mode === 'dark' ? 'LIGHT MODE' : 'DARK MODE'}
      </button>
    </header>
  );
}

function PageContent({ name }: { name: string }) {
  const { tokens } = useTheme();
  const [activeTab, setActiveTab] = useState('Design');
  const ComponentToRender = MAPPED_COMPONENTS[name];

  if (!ComponentToRender) return <div style={{ padding: 40 }}>Select a component</div>;

  return (
    <main style={{ marginLeft: 280, marginTop: 64, padding: '48px 64px', background: tokens.canvasDefault, minHeight: 'calc(100vh - 64px)' }}>
      <h1 style={{ fontSize: 48, fontWeight: 700, color: tokens.foregroundDefault, marginBottom: 40, fontFamily: typography.fontFamilies.primary }}>
        {name.replace(/([A-Z])/g, ' $1').trim()}
      </h1>

      <div style={{ display: 'flex', gap: 32, borderBottom: `1px solid ${tokens.modifiersMidlight}`, marginBottom: 48 }}>
        {['Design', 'Development', 'Accessibility'].map(tab => (
          <button
            key={tab}
            onClick={() => setActiveTab(tab)}
            style={{
              background: 'none', border: 'none', padding: '16px 0', fontSize: 16, cursor: 'pointer',
              color: activeTab === tab ? tokens.accentPrimaryDefault : tokens.foregroundDefault,
              borderBottom: activeTab === tab ? `4px solid ${tokens.accentPrimaryDefault}` : '4px solid transparent',
              fontWeight: activeTab === tab ? 600 : 400, opacity: activeTab === tab ? 1 : 0.6,
              fontFamily: typography.fontFamilies.primary
            }}
          >
            {tab}
          </button>
        ))}
      </div>

      {activeTab === 'Design' && (
        <div style={{
          background: tokens.elevationRaisedDefault, borderRadius: 12, padding: 64,
          border: `2px dashed ${tokens.accentPrimaryDefault}`, display: 'flex', justifyContent: 'center', alignItems: 'center'
        }}>
          <ComponentToRender>Previewing {name}</ComponentToRender>
        </div>
      )}

      {activeTab === 'Development' && (
        <pre style={{ background: tokens.elevationInsetDarker, padding: 32, borderRadius: 12, color: tokens.foregroundDefault, overflowX: 'auto' }}>
          <code>import { '{' } {name} { '}' } from '@lk/design-system';</code>
        </pre>
      )}
    </main>
  );
}

export default function App() {
  const [selected, setSelected] = useState(ALL_COMPONENTS.Components[0]);
  return (
    <ThemeProvider>
      <div style={{ backgroundColor: darkTheme.canvasDefault, minHeight: '100vh' }}>
        <Topbar />
        <Sidebar selected={selected} onSelect={setSelected} />
        <PageContent name={selected} />
      </div>
    </ThemeProvider>
  );
}
